name: buck2 build/run
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  buck-build-and-test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: facebook/install-dotslash@latest
      - uses: haskell-actions/setup@v2
      - run: echo "PATH=$(pwd):$PATH" >> $GITHUB_ENV
      - run: buck2 run cat4progs//breathing-test:main -v 2
